### ISSUE TITLE
Keep track of purging status when calling invalidate()

### ISSUE THREAD

**Issue by cam8001** [d8-contrib-modules/akamai#27]
Purging is handled via a Purge Purger plugin, which implements PurgerInterface.

If you look here, you can see what sort of response Purge expects in order to keep track of Purge status: 

https://github.com/nielsvm/purge/blob/8.x-3.x/src/Plugin/Purge/Purger/PurgerInterface.php#L66

Akamai keeps track of Purge status in its queues. We would need to track some state to keep a log of when things are _actually_ invalidated/purged upstream vs when the API request was made.

**Comment by cam8001** [comment]
Working away here: https://github.com/cam8001/akamai/tree/27/track-purge-status

**Comment by cam8001** [comment]
Remaining tasks:
- [x] - Implement form to delete logs
- [x] - Change StatusLog to StatusStorage (see BatchStorage for guidance)
- [x] - Create a Status class which encapsulates status responses
- [x] - Merge into 8.x-3.x
- [x] - Create a cron job that deletes purge status logs with a state of 'done' (needs to be configurable)
- [x] - Integrate purge status tracking with Purge module.

**Comment by neetumorwani** [comment]
@cam8001 I can see all the urls on '**admin/config/akamai/list**' (which are stored in purge queue) queued in for Akamai purging.
But I still see the requests not leaving 'In progress' state which is an issue from Akamai end and is worked upon by Akamai team as discussed here- 'https://community.akamai.com/thread/3613'.
The last issue not marked as complete here is - 'Integrate purge status tracking with Purge module'. We are integrating akamai with purge via the Plugin - 'AkamaiPurger' and I see the that we are calling the method [ purgeUrls on line 113](https://github.com/d8-contrib-modules/akamai/blob/8.x-3.x/src/Plugin/Purge/Purger/AkamaiPurger.php#L113) which in turn is saving the response status [by calling saveResponseStatus in AkamaiClient](https://github.com/d8-contrib-modules/akamai/blob/8.x-3.x/src/AkamaiClient.php#L272) IMO the task is done.
Just want to do double check if we are on the same page or Am I missing anything?
Thanks in advance.

**Comment by cam8001** [comment]
Are you using the development endpoint or a live one?

**Comment by neetumorwani** [comment]
Mock endpoint

**Comment by cam8001** [comment]
The mock endpoint status will never update, it just sends a static response.

**Comment by neetumorwani** [comment]
@cam8001 Thanks! I have updated the settings to point to the live environment. I have requested for purging a url and I see its (http://d8cdn.com/node/2) status as 'In Progress'. I am waiting for the status to change to something like done or etc. Any idea about the time it takes to purge a request?

**Comment by neetumorwani** [comment]
It says 'Done'. :)

**Comment by neetumorwani** [comment]
@cam8001 Since I do not see any tasks blocking the beta now. Can we  have the beta release of the module? 
I can continue working on making the tests better for the next release.
Thanks!

**Comment by cam8001** [comment]
I am gonna roll an alpha on April 1. Plans are here:
https://www.drupal.org/node/2678496

On 28 March 2016 at 11:56, neetumorwani notifications@github.com wrote:

> @cam8001 https://github.com/cam8001 Since I do not see any tasks
> blocking the beta now. Can we please have a beta release of the module?
> I can continue working on making the tests better for the next release.
> Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/d8-contrib-modules/akamai/issues/27#issuecomment-202340426

## 

Cameron Tod

Solutions Architect | Acquia http://www.acquia.com/gb

m: +44 7762 250 406
e: cameron.tod@acquia.com
w: http://www.acquia.com

Acquia Named a _Leader_ in new Gartner WCM Magic Quadrant
https://www.acquia.com/gartner-magic-quadrant

Follow @Acquia on Twitter http://www.twitter.com/Acquia

**Comment by neetumorwani** [comment]
Thanks a lot. @cam8001
